In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F
from d2l import torch as d2l

In [4]:
class Inception(nn.Module):
    def __init__(self, in_channels, c1, c2, c3, c4, **kwargs):
        super(Inception, self).__init__(**kwargs)
        
        self.p1_1 = nn.Conv2d(in_channels, c1, kernel_size=1)
        
        self.p2_1 = nn.Conv2d(in_channels, c2[0], kernel_size=1)
        self.p2_2 = nn.Conv2d(c2[0], c2[1], kernel_size=3, padding=1)
        
        self.p3_1 = nn.Conv2d(in_channels, c3[0], kernel_size=1)
        self.p3_2 = nn.Conv2d(c3[0], c3[1], kernel_size=3, padding=1)
        
        self.p4_1 = nn.Conv2d(in_channels, c4[0], kernel_size=3, padding=1)
        self.p4_2 = nn.COnv2d(c4[0], c4[1], kernel_size=1)
    
    def forward(self, x):
        p1 = F.relu(self.p1_1(x))
        p2 = F.relu(self.p2_2(F.relu(self.p2_1)))
        p3 = F.relu(self.p3_2(F.relu(self.p3_1)))
        p4 = F.relu(self.p4_2(F.relu(self.p4_1)))
        
        # 在channel维度上叠加
        return torch.cat((p1, p2, p3, p4), dim=1)

In [14]:
X = torch.randint(0, 5, size=(4, 2, 3, 3), dtype=float)
X, X.mean(dim=0)

(tensor([[[[2., 4., 0.],
           [2., 2., 3.],
           [2., 3., 3.]],
 
          [[3., 4., 2.],
           [4., 4., 0.],
           [4., 4., 0.]]],
 
 
         [[[3., 4., 3.],
           [0., 2., 0.],
           [0., 3., 4.]],
 
          [[2., 0., 3.],
           [2., 1., 1.],
           [3., 3., 0.]]],
 
 
         [[[2., 1., 0.],
           [0., 0., 3.],
           [2., 2., 4.]],
 
          [[3., 1., 0.],
           [2., 2., 2.],
           [2., 1., 3.]]],
 
 
         [[[3., 0., 0.],
           [0., 3., 0.],
           [0., 3., 2.]],
 
          [[0., 3., 3.],
           [2., 0., 3.],
           [0., 2., 4.]]]], dtype=torch.float64),
 tensor([[[2.5000, 2.2500, 0.7500],
          [0.5000, 1.7500, 1.5000],
          [1.0000, 2.7500, 3.2500]],
 
         [[2.0000, 2.0000, 2.0000],
          [2.5000, 1.7500, 1.5000],
          [2.2500, 2.5000, 1.7500]]], dtype=torch.float64))

In [2]:
weights = torch.ones((2, 10)) * 0.1
values = torch.arange(20.0).reshape((2, 10))
torch.bmm(weights.unsqueeze(1), values.unsqueeze(-1))

tensor([[[ 4.5000]],

        [[14.5000]]])

In [11]:
weights.unsqueeze(1).shape, values.unsqueeze(-1).shape

(torch.Size([2, 1, 10]), torch.Size([2, 10, 1]))