In [1]:
import torch

In [14]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [15]:
x.requires_grad_(True)  # 也可写成x = torch.arange(4.0, requires_grad=True)
x.grad  # 默认为none

In [16]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [17]:
y.backward()
x.grad  # y对x求导为4x

tensor([ 0.,  4.,  8., 12.])

In [18]:
x.grad.zero_()  # 计算另一个函数之前先，清零梯度，否则默认累积
print(x.grad)
y = x.sum()
y.backward()
x.grad

tensor([0., 0., 0., 0.])


tensor([1., 1., 1., 1.])

# 将部分计算移出计算图

In [20]:
x.grad.zero_()
y = x * x
u = y.detach()  # u在此不被看作函数，而被当成一个常量，其值等于x*x
z = u * x
z.sum().backward()
x.grad == u  # u被看作常数后，对z求导值为u

tensor([True, True, True, True])

In [23]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b .sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)  # 如果写成size=1，自动变成一个1*1的tensor；使用size=()则为标量
d = f(a)
d.backward()

a.grad == d/a

tensor(True)

tensor([-0.0389], requires_grad=True)
