In [5]:
%matplotlib inline
import torch
from d2l import torch as d2l

torch.set_printoptions(2)

In [2]:
def multibox_prior(data, sizes, ratios):
    pass

In [23]:
def IoU(boxes1, boxes2): 
    # (x1, y1, x2, y2)
    # boxes1 代表 锚框 共N个
    box_area = lambda boxes: ((boxes[:, 2] - boxes[:, 0]) * (boxes[:, 3] - boxes[:, 1]))
    
    areas1 = box_area(boxes1) #shape : (N, )
    areas2 = box_area(boxes2) #shape : (M, )
    # 借助None维度/unsqueeze来增加维度 即借助广播机制 计算每个box1 对 m 个box2的 max/min
    inter_upperlefts = torch.max(boxes1[:, None, :2], boxes2[:, :2])
    inter_lowerlefts = torch.min(boxes1[:, None, 2:], boxes2[:, 2:])
    
    # 限制最小值为0
    # inters shape: m n 2
    inters = (inter_lowerlefts - inter_upperlefts).clamp(min=0)
    
    inter_areas = inters[:, :, 0] * inters[:, :, 1]
    union_areas = areas1[:, None] + areas2 - inter_areas

In [24]:
boxes1 = torch.tensor([[1, 1, 3, 3], [4, 4, 2, 2], [3, 3, 2, 2]]) # 3 4
boxes2 = torch.tensor([[2, 2, 4, 4], [0, 0, 2, 2]])  # 2 4

boxes1[:, None, :2], boxes2[:, :2], torch.max(boxes1[:, None, :2], boxes2[:, :2])

(tensor([[[1, 1]],
 
         [[4, 4]],
 
         [[3, 3]]]),
 tensor([[2, 2],
         [0, 0]]),
 tensor([[[2, 2],
          [1, 1]],
 
         [[4, 4],
          [4, 4]],
 
         [[3, 3],
          [3, 3]]]))

In [26]:
box_iou(boxes1, boxes2)

torch.Size([3, 2, 2])


tensor([[0.14, 0.14],
        [0.00, 0.00],
        [0.00, 0.00]])